version: '3.8'

services:
  benchmark:
    build:
      context: ..
      dockerfile: spiderEval/Dockerfile
    volumes:
      - ..:/app
    networks:
      - text2sql-network
    working_dir: /app/spiderEval
    command: bash run_all_pipelines.sh

networks:
  text2sql-network:
    external: true
    name: text2sql-network
